// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3vQSORMaPzNn2PEg949vsLM9k1nc9EJI',
    appId: '1:315711735336:web:1c873022a2e1938cb2571d',
    messagingSenderId: '315711735336',
    projectId: 'momento-f1772',
    authDomain: 'momento-f1772.firebaseapp.com',
    storageBucket: 'momento-f1772.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCX1gn7EydDvP_agiha11IBFv4Ok2UmQE',
    appId: '1:315711735336:android:90cd3d7d1a8ed66fb2571d',
    messagingSenderId: '315711735336',
    projectId: 'momento-f1772',
    storageBucket: 'momento-f1772.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDINsM7Qe16xnL3Z9TTx75JpQ8PjkHfo5s',
    appId: '1:315711735336:ios:3abd9d21e69df443b2571d',
    messagingSenderId: '315711735336',
    projectId: 'momento-f1772',
    storageBucket: 'momento-f1772.appspot.com',
    iosBundleId: 'com.example.momento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDINsM7Qe16xnL3Z9TTx75JpQ8PjkHfo5s',
    appId: '1:315711735336:ios:13f59543d584fe23b2571d',
    messagingSenderId: '315711735336',
    projectId: 'momento-f1772',
    storageBucket: 'momento-f1772.appspot.com',
    iosBundleId: 'com.example.momento.RunnerTests',
  );
}
